name: Greetings

on:
  push:
      branches : ["master"]
jobs:
  greeting:
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/first-interaction@v1
    - name: List files
      run: ls -ltr
    - name: Echo simple message
      run : echo "Hellow Ganesh"
    
