name: Greetings

on:
  push:
      branches : ["master"]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v1 
    -name: List files
    run: ls -ltr
    - name: Echo simple message
    
